# Generated by Django 3.2.7 on 2021-10-29 14:22

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('subject', models.CharField(blank=True, max_length=127)),
                ('phone', models.CharField(blank=True, max_length=127)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Read', 'Read')], default='New', max_length=15)),
                ('ip', models.CharField(blank=True, max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('keywords', models.CharField(max_length=127)),
                ('description', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=127)),
                ('address', models.CharField(max_length=127)),
                ('phone', models.CharField(max_length=127)),
                ('fax', models.CharField(max_length=127)),
                ('email', models.CharField(max_length=127)),
                ('smtpserver', models.CharField(blank=True, max_length=127)),
                ('smtpemail', models.CharField(blank=True, max_length=127)),
                ('smtppassword', models.CharField(blank=True, max_length=127)),
                ('smtpport', models.CharField(blank=True, max_length=127)),
                ('icon', models.ImageField(blank=True, upload_to='icon_images/')),
                ('facebook', models.CharField(blank=True, max_length=127)),
                ('instagram', models.CharField(blank=True, max_length=127)),
                ('about_us', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('contact', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('references', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('status', models.CharField(choices=[('True', 'Evet'), ('False', 'Hayir')], max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
